### PR TITLE
WIP: Dockerfile_v5.8.0, docker fails on pip install clawpack

### PR DESCRIPTION
**Pull request by rjleveque**
Tries to change `clawpack-v5.8.0` to `clawpack-v5-8-0` and complains that metadata just says `clawpack`:
```
   ... egg=clawpack-v5.8.0 has inconsistent name: filename has 'clawpack-v5-8-0', but metadata has 'clawpack'
```
I haven't run into this before, and pip install works fine on my laptop.

Any ideas how to fix this?

Here's the error in context...

```
Step 12/20 : RUN pip install --src=/${HOME}/ --user -e git+https://github.com/clawpack/clawpack.git@v5.8.0#egg=clawpack-v5.8.0
 ---> Running in ac643ef45ab3
Obtaining clawpack-v5.8.0 from git+https://github.com/clawpack/clawpack.git@v5.8.0#egg=clawpack-v5.8.0
  Cloning https://github.com/clawpack/clawpack.git (to revision v5.8.0) to //home/jovyan/clawpack-v5-8-0
  Running command git clone -q https://github.com/clawpack/clawpack.git //home/jovyan/clawpack-v5-8-0
  Running command git submodule update --init --recursive -q
  WARNING: Generating metadata for package clawpack-v5.8.0 produced metadata for project name clawpack. Fix your #egg=clawpack-v5.8.0 fragments.
WARNING: Discarding git+https://github.com/clawpack/clawpack.git@v5.8.0#egg=clawpack-v5.8.0. Requested clawpack from git+https://github.com/clawpack/clawpack.git@v5.8.0#egg=clawpack-v5.8.0 has inconsistent name: filename has 'clawpack-v5-8-0', but metadata has 'clawpack'
ERROR: Could not find a version that satisfies the requirement clawpack-v5-8-0 (unavailable)
ERROR: No matching distribution found for clawpack-v5-8-0 (unavailable)
The command '/bin/sh -c pip install --src=/${HOME}/ --user -e git+https://github.com/clawpack/clawpack.git@v5.8.0#egg=clawpack-v5.8.0' returned a non-zero code: 1

```

### CODE REVIEW

**Comment by mandli** [comment]
Not sure, is there somewhere that `clawpack` is explicitly mentioned?

**Comment by rjleveque** [comment]
@mandli: Not sure what you mean... In the Dockerfile, clawpack-v5.8.0 is explicitly mentioned but not clawpack alone. Or do you mean in `setup.py`?  

I'm also not sure what metadata it is referring to in 
```
git+https://github.com/clawpack/clawpack.git@v5.8.0#egg=clawpack-v5.8.0 has inconsistent name: filename has 'clawpack-v5-8-0', but metadata has 'clawpack'
```

**Comment by mandli** [comment]
That was what I was referring to I guess although there are a bunch of things in the Python but would docker really pick that up?

**Comment by rjleveque** [comment]
Since the error message said `...Fix your #egg=clawpack-v5.8.0 fragments`, I tried it with simply 
```
RUN pip install --src=/${HOME}/ --user -e git+https://github.com/clawpack/clawpack.git@v5.8.0#egg=clawpack
```
and it got farther, but died after a ton of gfortran/f2py errors.  This may be part of our bigger problem with recent compilers that we need to tackle.

For now, I suggest people who want to use Docker start with the v5.7.1 version and install v5.8.0 themselves within a container, which works ok.  I added this to [the documentation](http://www.clawpack.org/docker_image.html).

Here's the final part of the error output when it dies, after all the warnings...
```
    In file included from /opt/conda/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1944,
                     from /opt/conda/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                     from /opt/conda/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/clawpack/pyclaw/classic/fortranobject.h:13,
                     from build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/clawpack/pyclaw/classic/fortranobject.c:2:
    /opt/conda/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
       17 | #warning "Using deprecated NumPy API, disable it with " \
          |  ^~~~~~~
    In file included from /opt/conda/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1944,
                     from /opt/conda/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                     from /opt/conda/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/clawpack/pyclaw/classic/fortranobject.h:13,
                     from build/src.linux-x86_64-3.7/clawpack/pyclaw/classic/classic1module.c:16:
    /opt/conda/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
       17 | #warning "Using deprecated NumPy API, disable it with " \
          |  ^~~~~~~
    build/src.linux-x86_64-3.7/clawpack/pyclaw/classic/classic1module.c:65:10: fatal error: threads.h: No such file or directory
       65 | #include <threads.h>
          |          ^~~~~~~~~~~
    compilation terminated.
    
    ########### EXT COMPILER OPTIMIZATION ###########
    Platform      :
      Architecture: x64
      Compiler    : gcc
    
    CPU baseline  :
      Requested   : 'min'
      Enabled     : SSE SSE2 SSE3
      Flags       : -msse -msse2 -msse3
      Extra checks: none
    
    CPU dispatch  :
      Requested   : 'max -xop -fma4'
      Enabled     : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_KNL AVX512_KNM AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL
      Generated   : none
    CCompilerOpt._cache_write[796] : write cache to path -> /home/jovyan/clawpack/build/temp.linux-x86_64-3.7/ccompiler_opt_cache_ext.py
    analyzeline: intent(callback) rpn2 is already in argument listanalyzeline: intent(callback) rpt2 is already in argument listanalyzeline: intent(callback) rpn3 is already in argument listanalyzeline: intent(callback) rpt3 is already in argument listanalyzeline: intent(callback) rptt3 is already in argument listanalyzeline: intent(callback) rpn2 is already in argument listanalyzeline: intent(callback) rpt2 is already in argument listerror: Command "gcc -pthread -B /opt/conda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ibuild/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/clawpack/pyclaw/classic -I/opt/conda/lib/python3.7/site-packages/numpy/core/include -Ibuild/src.linux-x86_64-3.7/numpy/distutils/include -I/opt/conda/include/python3.7m -I/opt/conda/include/python3.7m -c build/src.linux-x86_64-3.7/clawpack/pyclaw/classic/classic1module.c -o build/temp.linux-x86_64-3.7/build/src.linux-x86_64-3.7/clawpack/pyclaw/classic/classic1module.o -MMD -MF build/temp.linux-x86_64-3.7/build/src.linux-x86_64-3.7/clawpack/pyclaw/classic/classic1module.o.d -msse -msse2 -msse3" failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/conda/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'//home/jovyan/clawpack/setup.py'"'"'; __file__='"'"'//home/jovyan/clawpack/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --user --prefix= Check the logs for full command output.
```

**Comment by ketch** [comment]
I wonder if this is somehow related to my commit https://github.com/clawpack/clawpack/commit/77704a1824a227f16d53feca4dd10ae0daed991b.  If you remember, it used to be that setuptools would write the version number twice (e.g. clawpack-5.8.0.5.8.0) and in that commit I fixed the problem.  But perhaps I created a problem for Docker, or perhaps Docker was somehow relying on our earlier bug.

**Comment by rjleveque** [comment]
@ketch: That's possible. Looking at your commit, I wonder whether you should have deleted line [233](https://github.com/clawpack/clawpack/commit/77704a1824a227f16d53feca4dd10ae0daed991b#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L233)?

Maybe it was enough to get rid of `FULLVERSION` but you still need `VERSION` in the `setup_dict`?

**Comment by rjleveque** [comment]
There is now a v5.9.0 version and whatever the issue was here, it has been fixed.  

So I am closing this PR.

**Pull request closed without merging**
