### PR TITLE
add netcdf-enabled dockerfile

### PR DESCRIPTION
**Pull request by bolliger32**
I created a dockerfile that produces an image with NETCDF enabled. Passes nosetests.

### CODE REVIEW

**Comment by mandli** [comment]
I forgot to ask this, is this with the current master branch?

**Comment by bolliger32** [comment]
of clawpack? No this is with the v5.4.1 release. but it should work with the current master branch i'd imagine. The version of this dockerfile that we're using with our project has the current master branch (except for the geoclaw submod, which is the current commit of your new-storm-module branch)

**Comment by mandli** [comment]
Actually that's perfect.  When 5.5 is released (hopefully soon) we can update this as well.

**Comment by bolliger32** [comment]
👍

**Pull request merged**
